/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#09090b',
        'surface-container-low': '#0f0f12',
        'surface-container': '#121215',
        'surface-container-high': '#18181b',
        'surface-container-highest': '#1e1e22',
        'surface-bright': '#18181b',
        'surface-dim': '#0c0c0f',
        'surface-variant': '#18181b',
        'surface-tint': '#a78bfa',
        surface: '#0c0c0f',
        background: '#09090b',
        'on-background': '#fafafa',
        'on-surface': '#fafafa',
        'on-surface-variant': '#a1a1aa',
        'inverse-surface': '#fafafa',
        'inverse-on-surface': '#09090b',
        primary: '#a78bfa',
        'primary-fixed': '#ede9fe',
        'primary-fixed-dim': '#c4b5fd',
        'primary-container': '#7c3aed',
        'on-primary': '#0a0012',
        'on-primary-fixed': '#2e1065',
        'on-primary-fixed-variant': '#5b21b6',
        'on-primary-container': '#ede9fe',
        'inverse-primary': '#5b21b6',
        secondary: '#71717a',
        'secondary-fixed': '#a1a1aa',
        'secondary-fixed-dim': '#71717a',
        'secondary-container': '#27272a',
        'on-secondary': '#09090b',
        'on-secondary-fixed': '#18181b',
        'on-secondary-fixed-variant': '#3f3f46',
        'on-secondary-container': '#a1a1aa',
        tertiary: '#34d399',
        'tertiary-fixed': '#bbf7d0',
        'tertiary-fixed-dim': '#6ee7b7',
        'tertiary-container': '#065f46',
        'on-tertiary': '#001a12',
        'on-tertiary-fixed': '#003318',
        'on-tertiary-fixed-variant': '#047857',
        'on-tertiary-container': '#bbf7d0',
        outline: '#52525b',
        'outline-variant': '#27272a',
        error: '#ef4444',
        'error-container': '#3b1111',
        'on-error': '#1a0000',
        'on-error-container': '#fca5a5',
        medical: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          500: '#0284c7',
          600: '#0369a1',
          700: '#075985',
          800: '#0c4a6e',
          900: '#0a3751',
        },
        slate: {
          850: '#151e2e',
          950: '#0b0f19',
        },
        danger: {
          500: '#ef4444',
          600: '#dc2626',
        },
      },
      fontFamily: {
        headline: ['Geist', 'sans-serif'],
        display: ['Geist', 'sans-serif'],
        body: ['Geist', 'sans-serif'],
        label: ['Geist', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

